# Generated by Django 5.1.7 on 2025-05-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bridge_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_winner_needed',
            field=models.BooleanField(default=False, help_text='If True, the match needs a winner and it can be sometimes decided by a draw score.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one_draw_score',
            field=models.IntegerField(blank=True, help_text='The score of the match if it was a draw and it needed a winner.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two_draw_score',
            field=models.IntegerField(blank=True, help_text='The score of the match if it was a draw and it needed a winner.', null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='prediction_type',
            field=models.CharField(choices=[('numerical', 'Numerical'), ('player', 'Player'), ('boolean', 'Boolean')], default='numerical', help_text='Numerical: Expects a number (e.g., score, count).<br>Player: Expects a selection of a player (stores Player ID).<br>Boolean: Expects a Yes/No or True/False choice.', max_length=20),
        ),
    ]
