# Generated by Django 5.1.7 on 2025-05-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bridge_project', '0002_match_is_winner_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_bets', to='django_bridge_project.team'),
        ),
    ]
