# Generated by Django 5.1.7 on 2025-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bridge_project', '0003_bet_winner_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_calculation_done',
            field=models.BooleanField(default=False, help_text='True if points have been calculated and attributed for this finished match.'),
        ),
    ]
